### ISSUE TITLE
Error on the example

### ISSUE THREAD

**Issue by FurongYe** [souzamarcelo/cat#1]
As running the first example:
`python3 acviz.py --iracelog examples/acotsp-instances.Rdata --bkv examples/bkv.txt`

I have got error info:
```
Traceback (most recent call last):
  File "acviz.py", line 503, in <module>
    getPlot(
  File "acviz.py", line 438, in getPlot
    __plotTraining(data, restarts, showElites, showInstances, pconfig, overTime, showToolTips, instancesSoFar, mediansElite, mediansRegular, alpha)
  File "acviz.py", line 153, in __plotTraining
    ax2.set_xticklabels(instancesSoFar)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 63, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/axis.py", line 1793, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/matplotlib/axis.py", line 1714, in set_ticklabels
    raise ValueError(
ValueError: The number of FixedLocator locations (9), usually from a call to set_ticks, does not match the number of ticklabels (8).
```
Could you please help this? Thanks!

**Comment by souzamarcelo** [comment]
Thank you for reporting this issue. It didn't happen testing with Python <= 3.6. I fixed the problem with the size of the tick labels for instances used so far. It's working now!

**Comment by FurongYe** [comment]
Thanks! It works now!

I still got an warning info, probably you would be interested:
```
/usr/local/lib/python3.8/site-packages/numpy/ma/core.py:6849: RuntimeWarning: overflow encountered in power
  result = np.where(m, fa, umath.power(fa, fb)).view(basetype)
```

**Comment by souzamarcelo** [comment]
I will investigate that. Thank you again!
